### ISSUE TITLE
Add align map values

### ISSUE THREAD

**Issue by just-sultanov** [greglook/cljstyle#61] opened 2020-09-14 19:25 UTC
Hi! 
Thank you again for the `cljstyle`!
Can you add align map values? 
It would be great!

Something like this:
```clojure
(def my-map 
  {:a     "A value"
   :blarg :another-value
   :foo   {:test "A nested map"
           :c    :d}})
```

**Comment by greglook** [comment] 2020-11-06 04:32
Duplicate of #47

**Closed by greglook** 2020-11-06 04:32 UTC
Labels: duplicate
