### ISSUE TITLE
Garbling of non-ascii characters and emoji

### ISSUE THREAD

**Issue by licht1stein** [greglook/cljstyle#110] opened 2024-11-20 14:15 UTC
This happens on Fedora 41:

```sh
❯  echo "привіт" | cljstyle pipe
??????
```
It converts non-ascii characters to question marks. Same happens with emoji:

```sh
❯ echo "stop it! 😔😔😔" | cljstyle pipe
stop it! ???
```

**Comment by greglook** [comment] 2024-12-05 23:23
Duplicate of #108 - should be fixed in the next release!

**Closed by greglook** 2024-12-05 23:23 UTC
Labels: bug, duplicate
